addons:
ssh_known_hosts: stu-web4.uvu.edu

before_script:
  - echo -e "Host stu-web4.uvu.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config


language: php
php:
- 5.4
- 5.3
script: phpunit test/test.php

before_deploy:
- openssl aes-256-cbc -K $encrypted_53ef43865792_key -iv $encrypted_53ef43865792_iv -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- ssh-add deploy_key

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR erik@stu-web4.uvu.edu:/var && cp ~/database.json /var/www/lib
  on:
    branch: master

