language: php
php:
- 5.4
- 5.3
script: phpunit test/test.php

before_install:
- openssl aes-256-cbc -K $encrypted_53ef43865792_key -iv $encrypted_53ef43865792_iv
  -in deploy_key.enc -out deploy_key -d
