crfs:
  image: piuma/centos7-apache-php
  links:
    - maria
  volumes:
    - "./:/var/www"
    - "./docker-secrets:/var/secrets"
  ports:
    - "80:80"
    - "443:443"
  environment:
    - docker=true

maria:
  image: mariadb
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  volumes:
    - "./docker-secrets:/var/secrets"
  ports:
    - "3306:3306"
